[project]
authors = ["mantasm"]
entry = "lib.sw"
license = "Apache-2.0"
name = "interfaces"

[dependencies]
merkle = { path = "../libs/merkle" }
message = { path = "../libs/message" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.24.2" }
