[project]
authors = ["Emre Keskin"]
entry = "main.sw"
license = "Apache-2.0"
name = "gas-oracle"

[dependencies]
interfaces = { path = "../interfaces" }
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "master" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
