tokens:
    - chainName: sepolia
      standard: EvmHypCollateral
      decimals: 18
      symbol: ETH
      name: Ethereum
      addressOrDenom: '0x2fA4D5DD5a5BDb9A8889e37D94a3F35bca6d9Ea7'
      collateralAddressOrDenom: '0x2e5221B0f855Be4ea5Cefffb8311EED0563B6e87'

tokens:
    - chainName: sepolia
      standard: EvmHypSynthetic
      decimals: 18
      symbol: FST
      name: FuelSepoliaUSDC
      addressOrDenom: "0xb018793a4Bed2b5e859286786DFCD7eC0322a34E"

# tokens:
#     - chainName: sepolia
#       standard: EvmHypNative
#       decimals: 18
#       symbol: ETH
#       name: Ether
#       addressOrDenom: '0x532bBF2d770F3D5320E1EB9B250ade063662d48f'

tokens:
    - chainName: sepolia
      standard: EvmHypCollateral
      decimals: 6
      symbol: USDC
      name: USDC
      addressOrDenom: "0x31D85C771131a2aa2f572743B9C41f43dB8c8912"
      collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"


tokens:
    - chainName: sepolia
      standard: EvmHypCollateral
      decimals: 6
      symbol: USDC
      name: USDC
      addressOrDenom: "0x78026106472a7FB10668fED0301Af9dD321cf16B"
      collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"