[workspace]
resolver = "2"
members = [
  "contracts/mailbox",
  "contracts/validator-announce",
  "test-utils",
  "deploy",
  "e2e",
]


[workspace.dependencies]
fuels = "0.64.0"
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2024-04-25" }
hyperlane-core = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", rev = "befc38d" }
hyperlane-ethereum = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", rev = "befc38d" }
tokio = { version = "1.16.1", features = ["full"] }
