[workspace]
resolver = "2"
members = [
  "contracts/mailbox",
  "test-utils",
  "deploy",
  "e2e",
  "contracts/hooks/merkle-tree-hook",
  "contracts/hooks/igp",
  "contracts/test/merkle-test",
  "contracts/igp/gas-oracle",
  "contracts/igp/gas-paymaster",
  "contracts/validator-announce",

]


[workspace.dependencies]
fuels = "0.65.1"
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2024-04-25" }
hyperlane-core = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", rev = "befc38d" }
hyperlane-ethereum = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", rev = "befc38d" }
tokio = { version = "1.16.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.10.8"
serde_json = "1.0"
