[workspace]

members = [
  "contracts/mailbox",
  "contracts/warp-route",
  "contracts/igp/gas-paymaster",
  "contracts/igp/gas-oracle",
  "contracts/interfaces",
  "contracts/libs/merkle",
  "contracts/libs/message",
  "contracts/libs/std-lib-extended",
  "contracts/mocks/mock-post-dispatch",
  "contracts/mocks/mock-msg-recipient",
  "contracts/test/msg-recipient-test",
  "contracts/test/ism-test",
  "contracts/hooks/merkle-tree-hook",
  "contracts/hooks/igp",
  "contracts/test/merkle-test",
  "contracts/test/mailbox-test",
]
