[workspace]

members = [
  "contracts/mailbox",
  "contracts/warp-route",
  "contracts/interfaces",
  "contracts/libs/merkle",
  "contracts/libs/message",
  "contracts/libs/std-lib-extended",
  "contracts/libs/std-hook-metadata",
  "contracts/mocks/mock-post-dispatch",
  "contracts/mocks/mock-msg-recipient",
  "contracts/test/msg-recipient-test",
  "contracts/test/ism-test",
  "contracts/test/src20-test",
  "contracts/hooks/merkle-tree-hook",
  "contracts/hooks/fallback-domain-routing-hook",
  "contracts/hooks/gas-paymaster",
  "contracts/hooks/pausable-hook",
  "contracts/test/merkle-test",
  "contracts/test/mailbox-test",
  "contracts/validator-announce",
  "contracts/ism/multisig/merkle-root-multisig-ism",
  "contracts/ism/multisig/message-id-multisig-ism",
  "contracts/ism/aggregation-ism",
  "contracts/ism/routing/domain-routing-ism",
  "contracts/ism/routing/default-fallback-domain-routing-ism",
  "contracts/ism/libs/merkle-root-multisig-ism-metadata",
  "contracts/ism/libs/message-id-multisig-ism-metadata",
  "contracts/ism/libs/aggregation-ism-metadata",
  "contracts/libs/checkpoint",
  "contracts/gas-oracle",
]
