[project]
authors = ["Mantas Miklasevicius"]
entry = "main.sw"
license = "Apache-2.0"
name = "recipient"

[dependencies]
interfaces = { path = "../interfaces" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.24.2" }
