[project]
authors = ["Mantas Miklasevicius"]
entry = "main.sw"
license = "Apache-2.0"
name = "default-fallback-domain-routing-ism"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "master" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
interfaces = { path = "../../../interfaces" }
message = { path = "../../../libs/message" }
