[project]
authors = ["Mantas Miklasevicius"]
entry = "main.sw"
license = "Apache-2.0"
name = "multisig-ism"

[dependencies]
interfaces = { path = "../../interfaces" }
message = { path = "../../libs/message" }
multisig_ism_metadata = { path = "../multisig-ism-metadata" }
std_lib_extended = { path = "../../libs/std-lib-extended" }
merkle = { path = "../../libs/merkle" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.22.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
