[project]
authors = ["mantasm"]
entry = "main.sw"
license = "Apache-2.0"
name = "mailbox"

[dependencies]
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.21.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
interfaces = { path = "../interfaces" }
