[project]
authors = ["mantasm"]
entry = "main.sw"
license = "Apache-2.0"
name = "mailbox"

[dependencies]
sway_libs = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "master" }
interfaces = { path = "../interfaces" }
merkle = { path = "../libs/merkle" }
message = { path = "../libs/message" }
