[project]
authors = ["Mantas Miklasevicius"]
entry = "main.sw"
license = "Apache-2.0"
name = "pausable-hook"

[dependencies]
interfaces = { path = "../../interfaces" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.24.2" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.3" }
std_hook_metadata = { path = "../../libs/std-hook-metadata" }
