[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"


[dependencies]
ethers = { workspace = true }
hyperlane-core = { workspace = true }
# hyperlane-ethereum = { workspace = true }
fuels = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
