# A config for a Warp Route deployment
# Typically used with the 'hyperlane deploy warp' command
#
# Token Types:
#   native
#   collateral
#   synthetic
#
# see comprehensive [list](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/token/config.ts#L8)
---
test1:
  type: synthetic
  # token: "0x123" # Collateral/vault address. Required for collateral types
  owner: '0x0aE30543a22C74123D9c64F64B9Cb9bBB7268eEa' # Optional owner address for synthetic token
  mailbox: '0x8A791620dd6260079BF849Dc5567aDC3F2FdC318' # mailbox address route
  # interchainGasPaymaster: "0x123" # Optional interchainGasPaymaster address
  isNft: false # If the token is an NFT (ERC721), set to true
  # You can optionally set the token metadata
  name: 'SyntheticTokenRoute'
  symbol: 'STR'
  totalSupply: 10000000
  decimals: 18
