[package]
name = "deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
fuels = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
rand = "0.8.4"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9"
