[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
fuels = { workspace = true }
tokio = { workspace = true }
hyperlane-core = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
dotenv = "0.15"
once_cell = "1.10.0"
