[project]
authors = ["Emre Keskin"]
entry = "main.sw"
license = "Apache-2.0"
name = "token-router"

[dependencies]
interfaces = { path = "../../interfaces" }
message = { path = "../../libs/message" }
