[project]
authors = ["Emre Keskin"]
entry = "main.sw"
license = "Apache-2.0"
name = "aggregation"

[dependencies]
interfaces = { path = "../../interfaces" }
message = { path = "../../libs/message" }
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "master" }
std_hook_metadata = { path = "../../libs/std-hook-metadata" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
