[project]
authors = ["Emre Keskin"]
entry = "main.sw"
license = "Apache-2.0"
name = "validator-announce"

[dependencies]
interfaces = { path = "../interfaces" }
std_lib_extended = { path = "../libs/std-lib-extended" }
standards = { git = "https://github.com/FuelLabs/sway-standards", branch = "master" }
sway_libs = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }
